// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/base/button/Button.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/navigation/header/Header.vue')['default']
    Loader: typeof import('./components/base/loader/Loader.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
