// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/base/button/Button.vue')['default']
    Footer: typeof import('./components/navigation/footer/Footer.vue')['default']
    Header: typeof import('./components/navigation/header/Header.vue')['default']
    Loader: typeof import('./components/base/loader/Loader.vue')['default']
    Map: typeof import('./components/mapping/map/Map.vue')['default']
    ModelViewer: typeof import('./components/model-viewer/ModelViewer.vue')['default']
    NavItem: typeof import('./components/navigation/nav-item/NavItem.vue')['default']
    ProgressBar: typeof import('./components/base/progress-bar/ProgressBar.vue')['default']
    README: typeof import('./components/README.md')['default']
    StatCard: typeof import('./components/stats/stat-card/StatCard.vue')['default']
    StatList: typeof import('./components/stats/stat-list/StatList.vue')['default']
  }
}

export { }
